"""Render EXPERT_ACTIVATION_REPORT.md from expert_stats_summary.json + expert_stats.npz."""
import json
import numpy as np

S = json.load(open("/home/ubuntu/expert_stats_summary.json"))
Z = np.load("/home/ubuntu/expert_stats.npz")
layer_idxs = list(Z["layer_idxs"])
counts = Z["counts"]   # [L, 256]
coact = Z["coact"]     # [L, 256, 256]
NE = S["config"]["num_experts"]
TK = S["config"]["top_k"]

L = [f"# Laguna-XS.2 — MoE Expert Activation Report",
     "",
     f"**Model:** `{S['model']}`  ",
     f"**Corpus:** {S['corpus']['source']} — {S['corpus']['docs']} docs, "
     f"{S['corpus']['total_tokens']:,} tokens (seq_len ≤ {S['config']['seq_len']})  ",
     f"**Routing:** top-{TK} of {NE} experts per token, across "
     f"{S['config']['sparse_layers']} sparse-MoE layers (layer 0 is dense).",
     "",
     "Generated by forward-pass router introspection (hooks on every "
     "`LagunaTopKRouter`). Inspired by the RADLADS distillation framing "
     "(arXiv:2505.03005): measure what the sparse model actually uses before "
     "transferring it to a denser surrogate.",
     "",
     "## 1. Headline numbers",
     ""]

g = S["global"]
L += [
    f"- **Experts ever activated (any layer): {g['experts_ever_used']}/{NE} "
    f"({100*g['global_coverage']:.1f}%).**",
    f"- Mean per-layer coverage: **{100*g['mean_coverage_per_layer']:.1f}%** of "
    f"{NE} experts touched per layer.",
    f"- Mean **effective experts/layer** (exp-entropy of load): "
    f"**{g['mean_effective_experts']:.1f}** of {NE}.",
    f"- Mean load **Gini: {g['mean_gini_per_layer']:.3f}** "
    f"(0 = perfectly balanced, 1 = one expert does everything).",
    f"- Mean normalized routing entropy: **{g['mean_normalized_entropy']:.3f}** "
    f"(1.0 = uniform).",
    f"- Every token activates exactly {TK} experts by construction; the question "
    f"is how *concentrated* that usage is — see below.",
    "",
    "## 2. Per-layer expert usage",
    "",
    "| Layer | Tokens | Experts used | Coverage | Eff. experts | Gini | Max share | Dead |",
    "|------:|-------:|-------------:|---------:|-------------:|-----:|----------:|-----:|",
]
pl = S["per_layer"]
for i in layer_idxs:
    d = pl[str(i)]
    L.append(
        f"| {i} | {d['tokens']:,} | {d['experts_used']} | "
        f"{100*d['coverage']:.0f}% | {d['effective_experts']:.0f} | "
        f"{d['gini_load']:.3f} | {100*d['max_expert_share']:.1f}% | "
        f"{d['dead_experts']} |"
    )

# layer extremes
covs = [(i, pl[str(i)]["coverage"]) for i in layer_idxs]
ginis = [(i, pl[str(i)]["gini_load"]) for i in layer_idxs]
most_bal = min(ginis, key=lambda x: x[1])
least_bal = max(ginis, key=lambda x: x[1])
low_cov = min(covs, key=lambda x: x[1])

L += [
    "",
    "## 3. Balance & concentration",
    "",
    f"- Most **balanced** layer: **L{most_bal[0]}** (Gini {most_bal[1]:.3f}).",
    f"- Most **concentrated** layer: **L{least_bal[0]}** (Gini {least_bal[1]:.3f}).",
    f"- Lowest-coverage layer: **L{low_cov[0]}** "
    f"({100*low_cov[1]:.0f}% of experts used).",
    "",
]

# coactivation: aggregate across layers, find strongest co-firing pairs
L += ["## 4. Expert coactivation", "",
      "Within a token's top-8 set, which expert *pairs* fire together most often "
      "(relative to chance)? High lift = candidates to fuse/co-schedule when "
      "densifying. Aggregated over all sparse layers.", ""]

# build a global lift over a representative layer (mid-stack) + aggregate
agg = coact.sum(0)              # [256,256] total co-counts
diag = np.diag(agg).copy()
total_tok = sum(pl[str(i)]["tokens"] for i in layer_idxs)
# pairwise lift = P(i,j) / (P(i)P(j)); use counts
with np.errstate(divide="ignore", invalid="ignore"):
    pij = agg / total_tok
    pi = diag / total_tok
    lift = pij / np.outer(pi, pi)
lift[np.tril_indices(NE)] = 0
lift[~np.isfinite(lift)] = 0
# require minimum co-count to avoid noise
mask = agg < 50
lift[mask] = 0
flat = np.argsort(lift.ravel())[::-1][:10]
L += ["| Expert A | Expert B | Co-count | Lift |", "|---:|---:|---:|---:|"]
for f in flat:
    a, b = divmod(int(f), NE)
    if lift[a, b] <= 0:
        continue
    L.append(f"| {a} | {b} | {int(agg[a,b]):,} | {lift[a,b]:.2f}× |")

# busiest / quietest experts globally
glob = counts.sum(0)
order = np.argsort(glob)[::-1]
L += [
    "",
    "## 5. Busiest & quietest experts (global)",
    "",
    "Top 8 most-used experts (summed over all layers): "
    + ", ".join(f"E{int(e)} ({int(glob[e]):,})" for e in order[:8]),
    "",
    "8 least-used (non-dead) experts: "
    + ", ".join(f"E{int(e)} ({int(glob[e]):,})" for e in order[::-1][:8]),
    "",
    "## 6. Implications for MoE→dense densification",
    "",
    f"- With only ~**{g['mean_effective_experts']:.0f} effective experts** per "
    f"layer (of {NE}) on general C4 text, the routed FFN behaves far denser than "
    f"its 256-way capacity suggests — a dense surrogate MLP per layer has a "
    f"realistic target to reconstruct.",
    f"- Load Gini ≈ {g['mean_gini_per_layer']:.2f} means usage is skewed: a "
    f"dense surrogate should be fit preferentially on the high-traffic experts; "
    f"low-traffic experts contribute little to C4 activations.",
    "- The coactivation structure (§4) identifies experts that habitually fire "
    "together — natural groupings for block-wise densification or co-scheduling, "
    "matching this repo's *expert-coactivation-scheduling* premise.",
    "- Coverage is domain-dependent: C4 is general web text; code/math prompts "
    "would light up a different expert subset. A production densification set "
    "should mix domains so the surrogate isn't overfit to C4's active experts.",
    "",
    "## 7. Artifacts",
    "",
    "- `expert_stats.npz` — per-layer counts `[39,256]` and coactivation `[39,256,256]`.",
    "- `expert_stats_summary.json` — all per-layer + global metrics.",
    "- `expert_activation_analysis.py` — the introspection script.",
    "",
]

open("/home/ubuntu/EXPERT_ACTIVATION_REPORT.md", "w").write("\n".join(L))
print("wrote EXPERT_ACTIVATION_REPORT.md")
